imagePullSecret:
  create: true
  automaticReferenceInjection: true
  registry: R
  username: U
  email: e@domain.com
  password: P
imagePullSecrets: [a, b]

hub:
  config:
    # We pin these to avoid generating changes which cause diffs
    ConfigurableHTTPProxy:
      auth_token: aaaa1111
    JupyterHub:
      cookie_secret: bbbb2222
    CryptKeeper:
      keys: [cccc3333]
  extraFiles:
    my_config:
      mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/my_config.py
      stringData: |
        with open("/tmp/created-by-extra-files-config.txt", "w") as f:
            f.write("hello world!")
    binaryData1: &binaryData1
      mountPath: /tmp/binaryData.txt
      mode: 0666
      binaryData: |
        aGVsbG8gd
        29ybGQhCg==
    binaryData2: &binaryData2
      mountPath: /tmp/dir1/binaryData.txt
      mode: 0666
      binaryData: aGVsbG8gd29ybGQhCg==
    stringData1: &stringData1
      mountPath: /tmp/stringData.txt
      mode: 0666
      stringData: hello world!
    stringData2: &stringData2
      mountPath: /tmp/dir1/stringData.txt
      mode: 0666
      stringData: hello world!
    data-yaml: &data-yaml
      mountPath: /etc/test/data.yaml
      mode: 0444
      data:
        config:
          map:
            number: 123
            string: "hi"
          list: [1, 2]
    data-yml: &data-yml
      <<: *data-yaml
      mountPath: /etc/test/data.yml
    data-json: &data-json
      <<: *data-yaml
      mountPath: /etc/test/data.json
    data-toml: &data-toml
      <<: *data-yaml
      mountPath: /etc/test/data.toml
  service:
    type: ClusterIP
    ports:
      nodePort:
    extraPorts:
      - name: dummy-port-1
        port: 8181
        targetPort: 8181
      - name: dummy-port-2
        port: 8182
        targetPort: string-named-target-port
  baseUrl: /
  activeServerLimit: 3
  deploymentStrategy:
    type: Recreate
    rollingUpdate:
  labels: &labels
    mock-label1-key: mock-label1-value
    mock-label2-key: mock-label2-value
  annotations: &annotations
    mock-annotation1-key: mock-annotation1-value
    mock-annotation2-key: mock-annotation2-value
  db:
    type: sqlite-pvc
    upgrade:
    pvc:
      annotations: *annotations
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath: /mock
      storageClassName: custom-storage-class
    url: custom-db-url
  image:
    name: dummy-name
    tag: dummy-tag
    pullSecrets: [c]
  initContainers:
    - name: mock-init-container-name
      image: mock-init-container-image
  command:
    - tini
  args:
    - jupyterhub
    - "--mock-flag"
    - "{{ .Values.hub.baseUrl }}"
  extraConfig:
    test: |-
      c.Spawner.cmd = 'mock'
  extraEnv: &extraEnv
    IGNORED_KEY_NAME:
      name: MOCK_ENV_VAR_NAME1
      value: MOCK_ENV_VAR_VALUE1
    MOCK_ENV_VAR_NAME2:
      value: MOCK_ENV_VAR_VALUE2
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  resources: &resources
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
  lifecycle: &lifecycle
    postStart:
      exec:
        command:
          - "/bin/sh"
          - "-c"
          - "echo Hello from the postStart handler >> /usr/share/message"
    preStop:
      exec:
        command:
          - "/bin/sh"
          - "-c"
          - "echo Hello from the preStart handler >> /usr/share/message"
  services:
    tests:
      apiToken: mocked-api-token
  pdb:
    enabled: true
    maxUnavailable: 1
    minAvailable: null
  networkPolicy:
    enabled: true
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
    interNamespaceAccessLabels: ignore
    allowedIngressPorts: []
  allowNamedServers: true
  nodeSelector:
    node-type: mock
  tolerations:
    - key: mock-taint-key-hub
      operator: Equal
      value: mock-taint-value-hub
      effect: NoSchedule
  serviceAccount: &serviceAccount
    annotations: *annotations

rbac:
  enabled: true

proxy:
  service:
    extraPorts:
      - name: ssh
        port: 22
        targetPort: ssh
    type: LoadBalancer
    labels: *labels
    annotations: *annotations
    nodePorts:
      http:
      https:
  chp:
    extraCommandLineFlags:
      - "--auto-rewrite"
      - "--mock-flag {{ .Values.proxy.chp.resources.requests.memory }}"
    resources: *resources
    defaultTarget: http://dummy.local/hello
    errorTarget: http://dummy.local/error
    extraEnv: *extraEnv
    nodeSelector:
      node-type: mock
    tolerations:
      - key: mock-taint-key-chp
        operator: Equal
        value: mock-taint-value-chp
        effect: NoSchedule
    networkPolicy:
      enabled: true
      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
      interNamespaceAccessLabels: accept
      allowedIngressPorts: [http, https]
    pdb:
      enabled: true
      maxUnavailable: 1
      minAvailable: 1
  traefik:
    extraPorts:
      - name: ssh
        containerPort: 8022
    labels: *labels
    resources: *resources
    extraEnv: *extraEnv
    nodeSelector:
      node-type: mock
    tolerations:
      - key: mock-taint-key-traefik
        operator: Equal
        value: mock-taint-value-traefik
        effect: NoSchedule
    networkPolicy:
      enabled: true
      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
      interNamespaceAccessLabels: accept
      allowedIngressPorts: [http, https]
    pdb:
      enabled: true
      maxUnavailable: null
      minAvailable: 1
    serviceAccount: *serviceAccount
  secretSync:
    resources: *resources
  labels: *labels
  https:
    enabled: true
    type: letsencrypt
    #type: letsencrypt, manual, offload, secret
    letsencrypt:
      contactEmail: "e@domain.com"
    manual:
      key: mock-key
      cert: mock-cert
    secret:
      name: "mock-secret-name"
      key: "mock-key"
      crt: "mock-crt"
    hosts: [domain.com]

singleuser:
  profileList:
    - display_name: "mock display name 1"
      description: |
        mock description 1
      default: True
    - display_name: "mock display name 2"
      description: |
        mock description 2
      kubespawner_override:
        image: XYZ:XYZ
  nodeSelector:
    mock-node-selector: mock
  extraTolerations:
    - effect: NoSchedule
      key: mock-taint-key-singleuser
      operator: Equal
      value: mock-taint-value-singleuser
  extraNodeAffinity:
    required:
      - matchExpressions:
          - key: hub.jupyter.org/test-required-node
            operator: In
            values: [test]
    preferred:
      - weight: 10
        preference:
          matchExpressions:
            - key: hub.jupyter.org/test-preferred-node
              operator: In
              values: [test]
  extraPodAffinity:
    required:
      - labelSelector:
          matchExpressions:
            - key: hub.jupyter.org/test-required-pod
              operator: In
              values: [test]
        topologyKey: failure-domain.beta.kubernetes.io/zone
    preferred:
      - weight: 10
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: hub.jupyter.org/test-preferred-pod
                operator: In
                values: [test]
          topologyKey: kubernetes.io/hostname
  extraPodAntiAffinity:
    required:
      - labelSelector:
          matchExpressions:
            - key: hub.jupyter.org/test-required-anti-pod
              operator: In
              values: [test]
        topologyKey: failure-domain.beta.kubernetes.io/zone
    preferred:
      - weight: 10
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: hub.jupyter.org/test-preferred-anti-pod
                operator: In
                values: [test]
          topologyKey: kubernetes.io/hostname
  cloudMetadata:
    blockWithIptables: true
    ip: 169.254.169.254
  networkPolicy:
    enabled: true
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
    interNamespaceAccessLabels: ignore
    allowedIngressPorts: []
  events: true
  extraLabels: *labels
  extraEnv: *extraEnv
  lifecycleHooks: *lifecycle
  initContainers:
    - name: mock-init-container-name
      image: mock-init-container-image
      imagePullSecret: IfNotPresent
  extraContainers:
    - name: mock-extra-container-name
      image: mock-extra-container-image
      imagePullPolicy: IfNotPresent
  uid: 1000
  fsGid: 100
  serviceAccountName:
  storage:
    type: dynamic
    extraLabels: *labels
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: "{username}"
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  startTimeout: 300
  cpu:
    guarantee: 0.2
    limit: 4
  memory:
    guarantee: 1G
    limit: 8G
  extraResource:
    guarantees:
      mock: 3
    limits:
      mock: 1
  cmd: jupyterhub-singleuser
  defaultUrl: /

scheduling:
  userScheduler:
    enabled: true
    replicas: 1
    logLevel: 10
    image:
      name: gcr.io/google_containers/kube-scheduler-amd64
      tag: v1.11.2
    nodeSelector:
      node-type: mock
    tolerations:
      - key: mock-taint-key-scheduling
        operator: Equal
        value: mock-taint-value-scheduling
        effect: NoSchedule
    plugins:
      score:
        disabled:
          - name: SelectorSpread
        enabled:
          - name: NodePreferAvoidPods
            weight: 161051
          - name: NodeAffinity
    serviceAccount: *serviceAccount
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 1
    resources: *resources
  corePods:
    tolerations:
      - key: mock-taint-key-corePods
        operator: Equal
        value: mock-taint-value-corePods
        effect: NoSchedule
    nodeAffinity:
      matchNodePurpose: require
  userPods:
    tolerations:
      - key: mock-taint-key-userPods
        operator: Equal
        value: mock-taint-value-userPods
        effect: NoSchedule
    nodeAffinity:
      matchNodePurpose: require

prePuller:
  extraTolerations:
    - key: mock-taint-key-prePuller
      operator: Equal
      value: mock-taint-value-prePuller
      effect: NoSchedule
  hook:
    enabled: true
    nodeSelector:
      node-type: mock
    tolerations:
      - key: mock-taint-key-hook
        operator: Equal
        value: mock-taint-value-hook
        effect: NoSchedule
    serviceAccount: *serviceAccount
  continuous:
    enabled: true
  extraImages:
    mockImage1:
      name: mock-user/mock-image1
      tag: mock-tag
    mockImage2:
      name: mock-user/mock-image2
      tag: mock-tag

ingress:
  enabled: true
  annotations: *annotations
  hosts:
    - mocked1.domain.name
    - mocked2.domain.name
  tls:
    - secretName: jupyterhub-tls
      hosts:
        - mocked1.domain.name
        - mocked2.domain.name

cull:
  enabled: true
  users: true
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 28800

debug:
  enabled: true

global:
  whatever:
    this-should-be-accepted: true

custom:
  myCustomStuff: [hello]
